
version: '3'
services:
  db:
    image: 'supabase/postgres:15.1.0.148'
    ports:
      - '6432:5432'
    volumes:
      - './dev/postgres:/docker-entrypoint-initdb.d/'
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_HOST=/var/run/postgresql
      - PGPORT=${POSTGRES_PORT:-5432}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - PGPASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - PGDATABASE=postgres
      - POSTGRES_DB=postgres

      - JWT_SECRET=${SERVICE_PASSWORD_JWT}
      - JWT_EXP=${JWT_EXPIRY:-3600}
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
  supavisor:
    build: .
    ports:
      - 4000:4000
      - 5452:5452
      - 6543:6543
    environment:
      - PORT=4000
      - PROXY_PORT_SESSION=5452
      - PROXY_PORT_TRANSACTION=6543
      - DATABASE_URL='ecto://postgres:${SERVICE_PASSWORD_POSTGRES}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/postgres'
      - CLUSTER_POSTGRES=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - VAULT_ENC_KEY=${VAULT_ENC_KEY}
      - API_JWT_SECRET=${JWT_SECRET}
      - METRICS_JWT_SECRET=dev
      - REGION=local
      - ERL_AFLAGS='-proto_dist inet_tcp'
    command: 'sh -c "/app/bin/migrate && /app/bin/server"'
    depends_on:
      - db
